# https://projecteuler.net/problem=2 (note: project euler doesn't want public sharing of solutions beyond problems 1-100)

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

i = 1
j = 2
new_number = 3

fibonacci = [1, 2] 

while new_number <= 4000000:
    if new_number % 2 == 0:
        fibonacci.append(new_number)
    # lines 21, 22, and 24 just properly increment the numbers to add up to the next number in the sequence
    i = j
    j = new_number
    print(new_number) # this is just to test that the right numbers are being generated
    new_number = i + j 

print(fibonacci) # just testing to make sure only the even numbers were added
print("The answer to euler problem 2 is: ", sum(fibonacci) - 1) # minus one, because I started with that for completeness